### ISSUE TITLE
Clicking token icon doesn't work

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#1703]
On this page: https://map.treetracker.org/tokens/254fd088-b0aa-4eef-a3d9-b02c491ff9d3?bounds=47.21599817276002,-18.561482861162506,47.2314476966858,-18.54671429311487

Clicking other token icon on the map doesn't change the page to token clicked.
<img width="1432" alt="image" src="https://github.com/Greenstand/treetracker-web-map-client/assets/5744708/0d27d9b5-d540-45e4-9562-3f4f6857db3a">

But on this page for tree point, it works.

https://map.treetracker.org/trees/5442304

**Comment by ANIRUDH-GHUB** [comment]
If this is still open, I can try fixing this. Can you assign this to me please

**Comment by dadiorchen** [comment]
@ANIRUDH-GHUB yea, this is a valid issue!

**Comment by ANIRUDH-GHUB** [comment]
Thanks for assigning. I will start working on it

**Comment by henlam1** [comment]
Hi @dadiorchen , I want to attempt fixing this issue if it's still available.

**Comment by dadiorchen** [comment]
@henlam1 yes, please take it

**Comment by henlam1** [comment]
@dadiorchen I'm looking at pathResolver.js and it seems that when we click on a new token, the same URL gets reused which is why we keep seeing the same tree. We need to get the token id to update the URL but I'm having some trouble.

Is there a way to add the token id to the tree object? Or is there a function that takes in a tree's id and returns its token id?
<img width="715" alt="Screenshot 2023-09-12 135403" src="https://github.com/Greenstand/treetracker-web-map-client/assets/89503456/c813ba85-ac5d-4634-8fa5-908d1d6a926c">

**Comment by dadiorchen** [comment]
Great question, thank you for taking the time to analyze this. 

The answer is yes, you can use the query api to get the token_id by tree id: https://prod-k8s.treetracker.org/query/trees/5442304
