### ISSUE TITLE
Write document about how to write integration test.

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#685]
This issue just is about writing a guide in the REAMDE.md, please:

* Read the code and understand how the integration tests work, files under: `/cypress/tests/integrations/`
* Write a guide about how to create new integration and briefly describe how does this work.

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by keyy123** [comment]
@dadiorchen I would like to learn how to do integration testing for cypress and document the process as well!

**Comment by dadiorchen** [comment]
Oh, that's great, please let me know if you need any assistance, here or slack

**Comment by keyy123** [comment]
Rough Draft:

Cypress Integration Testing Documentation [Draft]

// Where to find the integration testing files

Within the root, Go to 'cypress' directory. Next, Select the 'tests' 
dir then 'integration. Depending on what you are a testing make the
appropriate directory to test it. 

// File Naming Convention

When making an integration testing file, Be sure to name it
**.cy.js. This file extension name allows cypress to reckonize 
the file as a cypress test. 

//File Placement 

When adding a Cypress test within the 'integration', Cypress
will consider the test an integration test. 

*An integration test is a test where individual software units
units aka unit tests are bundled and tested together. * 

* cypress 
 |
 => tests
    |
    => integration 
       |
        => **.cy.js === integration test (Good)

* src/component
  |
  => **.cy.js === unit test/component test (Not Integration test)


// Utilize Existing Best Practices As Much As Possible

After writing your first successful test in Cypress,
It is a good to revise it using current testing best practices.
Luckily, The Cypress team's documentation has many of the best practices 
recorded here (docs.cypress.io/guides/references/best-practices)


// Where does nockIntercept come from?

Look in cypress/plugins/index.js. It seems like a basic
http server that mocks nextjs routes based on the url, path, 
HTTP method and body passed in *and statusCode*. 


// Setup for integration testing

1) import prepareNocks and clearNocks

2) Import the required fixtures (files with a fixed set of data we want to use)
into your test as well (cypress/fixtures or doc/examples)

3) setup a beforeEach hook that invokes clearNocks
before each test

4) Make a test (with multiple assertions) that completes a task that you want 
cypress to complete that involves the interaction of many units/modules

(Example: Login => visit home page => visit organizations => find organization that contains
FCC in its name)

note: Read the getNockRoutes to see which routes are usable for prepareNocks method
(cypress/tests/integration/nockRoutes.js)


Practice: Setup a route 

Note: This will be done in your cloned/fork of the web-map-client repo

1.) Make a new integration test called 'money_tree.cy.js

2.) Make a default import for the tree186734.json fixture from fixtures folder

note: Since, We are testing a tree we will need some tree data which is why we
imported the tree json data from fixtures. This is the same logic used in the other 
integration test

3.) Make 2 named imports for prepareNocks and clearNocks 

note: Almost all of the Integration test use these 2 named
imports.

4.) Setup a beforeEach hook that invokes clearNocks -
this remove partial state that would influence other test
using nockIntercept/nocks *I think*

beforeEach(()=>{
  clearNocks();
});

5.) Make a variable that contains the path for the route 
you want to call. In our case, /trees/${tree.id} 

Example: 

localhost:3000    /money
[hostname]        [path]

tip: most/all paths you would want to use are located in the 
nockRoutes.js file. Be sure to use backticks. 

However, If the path is not in the folder and you are lost don't be afraid to ask in the 
team's slack channel. You'll find an answer within 24 hours or less depending on when
you ask.

6.) If you are testing an image, You may need to use cy.fixture and promise chain it 
to turn the picture to a base64 blob and make a URL from the blob.

const blob = Cypress.Blob.base64StringToBlob(image, 'image/[type]');
const url = Cypress.Blob.createObjectURL(blob);

[image] is a placeholder for the file type

7.) Invoke prepareNocks and pass in one of the props it uses
and copy the fixture object values and over-write the specfic value you are
testing

prepareNocks({
  tree: {...tree, species_name: "money tree"}
});


8.) Use cy.task - 'nockIntercept' to mock an API call
with the hostname, HTTP method, path, expected status code and
the body if any

note: This can get a bit tricky here. Within an integration test, Use this task 
to make mock calls for all of the endpoints you are expecting to use in the actual 
page. 


cy.task('nockIntercept', {
  hostname: 'https://dev-k8s.treetracker.org',
  method: 'get',
  path: '/query/trees/951836',
  statusCode: 200,
  body: {
	id:951836,
      planterid: 940
  },
});


Example:


If you do an API call for a specific token, You need to do an API call for a specific wallet since 
a token belongs to the wallet of a user, which belongs to a transaction and linked to a tree.

Once again, Ask for help on the team slack


What does prepareNocks do? 

When would you use nockIntercept vs visiting a path?

Simple test like checking if an image was changed uses visit 
while more complex test utilizing several endpoints will call for
multiple nockIntercept calls.


Basic Practices to consider? 

* Run shared code before each test

* Do not create tiny-One assertion tests in E2E/Integration testing

**Comment by dadiorchen** [comment]
Oh, this is good! thank you @keyy123 you can put it into the readme or any appropriate place you think

**Comment by keyy123** [comment]
Sounds good!
