### ISSUE TITLE
XML parsing error on page load

### ISSUE THREAD

**Issue by michaltrunek** [Greenstand/treetracker-web-map-client#75]
```
XML Parsing Error: not well-formed
Location: https://treetracker-map-features.fra1.digitaloceanspaces.com/freetown_catchments.geojson
```

**Details:**
Firefox browser

![Screenshot 2021-06-25 at 16 42 11](https://user-images.githubusercontent.com/4280850/123459025-064f8080-d5e6-11eb-934d-388e5632be70.png)

**Comment by dadiorchen** [comment]
Yes, this is a valid bug

**Comment by mrtillman** [comment]
@dadiorchen @michaltrunek 

so, how do I reproduce this error?

I've loaded test.treetracker.org, but I do not see the `XML Parsing Error` shown in the screenshot.

**Comment by mrtillman** [comment]
I can start on this one

**Comment by mrtillman** [comment]
@michaltrunek @dadiorchen 

do we control the code that defines https://treetracker-map-features.fra1.digitaloceanspaces.com?

I ask because the `/freetown_catchments.geojson` resource does not return a `Content-Type` header. as a result, Firefox assumes the response content is XML and chokes when trying to parse the JSON as XML. see more details about this [here](https://stackoverflow.com/questions/7642202/xml-parsing-error-not-well-formed-in-firefox-but-good-in-chrome).

if we do control the code, please let me know where the repo is for https://treetracker-map-features.fra1.digitaloceanspaces.com.

thanks.

**Comment by dadiorchen** [comment]
@ZavenArra can you give me the details of the geojson for Freetown, like the cloud setting up, we might need to do so adjustment.
