### ISSUE TITLE
Refactor the tab to better support for the SEO

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#817]
Our tabs on the page is using javascript to switch , it may cause SEO problem, need to consider a better approach.

![Image](https://user-images.githubusercontent.com/5744708/185057460-698c4bad-3df4-4eea-869a-a2a7ef04bd65.png)

Here is some resource: https://www.seroundtable.com/google-hidden-tab-content-seo-19489.html

**Comment by RubenSmn** [comment]
Maybe we could only change the sx prop `display` instead of hiding all the content: https://github.com/Greenstand/treetracker-web-map-client/blob/beta/src/pages/organizations/%5Borganizationid%5D.js#L384
Something like the approach found on the MUI Hidden page https://mui.com/material-ui/migration/v5-component-changes/#hidden

**Comment by dadiorchen** [comment]
Yea, that's a way, I'm not sure this is good for google, they might ignore the invisible block in the page

**Comment by dadiorchen** [comment]
https://developers.google.com/search/docs/advanced/guidelines/hidden-text-links?hl=en&visit_id=637963843889451599-646526783&rd=1
