### ISSUE TITLE
On mobile, the map can not display trees correctly for this wallet

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#844]
http://localhost:3000/wallets/eecdf253-05b6-419a-8425-416a3e5fc9a0

![Image](https://user-images.githubusercontent.com/5744708/185834424-0eadf5d6-00bb-44f4-a902-2ed24e87084d.png)

But if switch to desktop, it is fine.

**Comment by jeremydthomas** [comment]
@dadiorchen its because the trees are spread out to 3 different continents and it sets the zoomLevel to 1 to try to include all of the trees in such a small screen space. When you are at zoom Level 1 you cant see anything on the map. Not only that, the minZoom is set to 2 so it kind of messes everything up.  If you set the zoomLevel to 2, you can see some of the tree markers. 

Heres a video where I set the zoomLevel to 2, and then I change it back to zoomLevel 1 so you can see what I mean.


https://user-images.githubusercontent.com/63400531/190059724-04d9b94b-8fcc-4487-9b1d-e9764602befc.mp4

**Comment by dadiorchen** [comment]
Oh, @jeremydthomas you are my hero, can you open a PR for this?

**Comment by jeremydthomas** [comment]
Thanks! Yes I will when I get home
