### ISSUE TITLE
Use the uuid component to display this tag

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#845]
The uuid is too long, need to use the component mentioned in this issue #823  to shorten the tag.

Also, this page: http://localhost:3000/wallets/eecdf253-05b6-419a-8425-416a3e5fc9a0

![Image](https://user-images.githubusercontent.com/5744708/185835681-0e46d9a3-a191-4485-b8f3-3fd8e2ab266a.png)

**Comment by tyler1588** [comment]
I'd be happy to take this one.
If I understand correctly, this change is waiting on the component from #823?

**Comment by dadiorchen** [comment]
Correct, @tyler1588 thank you for taking this issue

**Comment by RubenSmn** [comment]
@tyler1588 #823 is fixed

**Comment by tyler1588** [comment]
@RubenSmn Great, thank you. I will get started on this.

**Comment by tyler1588** [comment]
I am attempting to run the tokenid test so that I can work on this issue (I haven't modified anything yet) and the test is failing. Is there a different way I can access an example UUID to work on this?

<img width="838" alt="Screen Shot 2022-09-04 at 10 45 14 PM" src="https://user-images.githubusercontent.com/87100297/188350940-1a06f956-934c-441a-abbd-aa169a613ac3.png">

**Comment by RubenSmn** [comment]
@tyler1588 you can see the tag on http://localhost:3000/tokens/6c85c551-ed63-456f-ba0f-8d632897f560 or on the wallet page Dadior mentioned

**Comment by RubenSmn** [comment]
@tyler1588 to fix the cypress issue run `npm run cy:nock`
