### ISSUE TITLE
Failed to use pre-cache feature by next.js

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#857]
@okdv I failed to release the new version to prod env, please help me analyze, this is the error: https://github.com/Greenstand/treetracker-web-map-client/runs/7990205499?check_suite_focus=true

Seems we can not build next now, can you check it on your side?

**Comment by dadiorchen** [comment]
And another thing I noticed is that when open /top locally, the logo is missing, previously they were there.



![Image](https://user-images.githubusercontent.com/5744708/186369589-2f03bb86-2558-4b47-89b0-b297a912dced.png)

**Comment by okdv** [comment]
figured it out, this points to my change in the PR for [data] instead of data.planters / data.organizations

root cause was MSW was returning only a single object of a planter or org, instead of an array of planters/orgs that we get in the prod api. so the hot fix i made in that PR worked with MSW but not prod api. PR coming shortly

**Comment by dadiorchen** [comment]
Good, I think now we are not so relying on the MSW right? I remember we are using it for mocking data, but now the nock + axios-mock works well I guess.

**Comment by okdv** [comment]
@dadiorchen that may be the case, im not too sure, I think that predates when I started contributing here and havent looked to far into it. But I've been using npm run dev:mock for local testing and I was under the impression this was using msw. perhaps we could look into cleaning up some of these stale dependencies?
